trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: .paket\paket.bootstrapper.exe
  displayName: 'Install paket'
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npx webpack
  displayName: 'Install packages and build'
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)\deploy'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: Publish
