trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: .paket\paket.bootstrapper.exe
  displayName: 'Install paket'

- script: dotnet restore
  displayName: 'Restore dotnet packages'

- script: dotnet run --project test\AuroraBlueprints.Tests.fsproj
  displayName: 'Run tests'
 
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install packages'

- script: npx webpack
  displayName: 'Build'  
 
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)\deploy'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish app'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/TestResults.xml'
  displayName: 'Publish test results'

